import React from "react";
import { TableBlock } from "../components/runtime/TableBlock";

const Bracketslot: React.FC = () => {
  return (
    <div id="page-bracketslot-19">
    <div id="ifaxkui" style={{"height": "100vh", "fontFamily": "Arial, sans-serif", "display": "flex", "--chart-color-palette": "default"}}>
      <nav id="ix7ad0o" style={{"width": "250px", "padding": "20px", "display": "flex", "overflowY": "auto", "background": "linear-gradient(135deg, #4b3c82 0%, #5a3d91 100%)", "color": "white", "--chart-color-palette": "default", "flexDirection": "column"}}>
        <h2 id="izekdr5" style={{"fontSize": "24px", "fontWeight": "bold", "marginTop": "0", "marginBottom": "30px", "--chart-color-palette": "default"}}>{"BESSER"}</h2>
        <div id="is68mar" style={{"display": "flex", "--chart-color-palette": "default", "flexDirection": "column", "flex": "1"}}>
          <a id="iwzhyn3" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/channel">{"Channel"}</a>
          <a id="idzlblc" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/channelmember">{"ChannelMember"}</a>
          <a id="i5ct4tj" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/competition">{"Competition"}</a>
          <a id="igpfcnx" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/favoritecompetition">{"FavoriteCompetition"}</a>
          <a id="iqqlpp2" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/favoriteteam">{"FavoriteTeam"}</a>
          <a id="ifai8rb" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/friendship">{"Friendship"}</a>
          <a id="i16rney" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/match">{"Match"}</a>
          <a id="ini1cvk" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/matchevent">{"MatchEvent"}</a>
          <a id="imwj5ke" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/message">{"Message"}</a>
          <a id="i0tmlpf" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/notification">{"Notification"}</a>
          <a id="i2vb235" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/player">{"Player"}</a>
          <a id="i1alkzl" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/reaction">{"Reaction"}</a>
          <a id="it9qw7j" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/sport">{"Sport"}</a>
          <a id="iuu7unk" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/standing">{"Standing"}</a>
          <a id="ix2bfbr" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/team">{"Team"}</a>
          <a id="ilzab0c" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/user">{"User"}</a>
          <a id="ikcgppm" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/matchstatistics">{"MatchStatistics"}</a>
          <a id="ijitvah" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/favoriteplayer">{"FavoritePlayer"}</a>
          <a id="ioh6hxj" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/tournamentround">{"TournamentRound"}</a>
          <a id="iuu4q7i" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "rgba(255,255,255,0.2)", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/bracketslot">{"BracketSlot"}</a>
          <a id="ie0944v" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/mediafile">{"MediaFile"}</a>
          <a id="ip0edaa" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/stadium">{"Stadium"}</a>
          <a id="ijy8amk" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/lineup">{"Lineup"}</a>
          <a id="iysl22n" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/lineupplayer">{"LineupPlayer"}</a>
          <a id="imwf6ij" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/prematchodds">{"PreMatchOdds"}</a>
          <a id="ia8fs6y" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/matchpreview">{"MatchPreview"}</a>
          <a id="il4x6xt" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/tennisset">{"TennisSet"}</a>
        </div>
        <p id="idtqd5c" style={{"fontSize": "11px", "paddingTop": "20px", "marginTop": "auto", "textAlign": "center", "opacity": "0.8", "borderTop": "1px solid rgba(255,255,255,0.2)", "--chart-color-palette": "default"}}>{"© 2026 BESSER. All rights reserved."}</p>
      </nav>
      <main id="ihp3y27" style={{"padding": "40px", "overflowY": "auto", "background": "#f5f5f5", "--chart-color-palette": "default", "flex": "1"}}>
        <h1 id="igvh5hv" style={{"fontSize": "32px", "marginTop": "0", "marginBottom": "10px", "color": "#333", "--chart-color-palette": "default"}}>{"BracketSlot"}</h1>
        <p id="i18145r" style={{"marginBottom": "30px", "color": "#666", "--chart-color-palette": "default"}}>{"Manage BracketSlot data"}</p>
        <TableBlock id="table-bracketslot-19" styles={{"width": "100%", "minHeight": "400px", "--chart-color-palette": "default"}} title="BracketSlot List" options={{"showHeader": true, "stripedRows": false, "showPagination": true, "rowsPerPage": 5, "actionButtons": true, "columns": [{"label": "Id", "column_type": "field", "field": "id", "type": "str", "required": true}, {"label": "Position", "column_type": "field", "field": "position", "type": "int", "required": true}, {"label": "Equipe Domicile Id", "column_type": "field", "field": "equipe_domicile_id", "type": "str", "required": true}, {"label": "Equipe Exterieur Id", "column_type": "field", "field": "equipe_exterieur_id", "type": "str", "required": true}, {"label": "Vainqueur Id", "column_type": "field", "field": "vainqueur_id", "type": "str", "required": true}, {"label": "Est Qualifie", "column_type": "field", "field": "est_qualifie", "type": "bool", "required": true}, {"label": "Tour", "column_type": "lookup", "path": "tour", "entity": "TournamentRound", "field": "id", "type": "str", "required": true}, {"label": "Match", "column_type": "lookup", "path": "match", "entity": "Match", "field": "created_at", "type": "datetime", "required": true}], "formColumns": [{"column_type": "field", "field": "id", "label": "id", "type": "str", "required": true, "defaultValue": null}, {"column_type": "field", "field": "position", "label": "position", "type": "int", "required": true, "defaultValue": null}, {"column_type": "field", "field": "equipe_domicile_id", "label": "equipe_domicile_id", "type": "str", "required": false, "defaultValue": null}, {"column_type": "field", "field": "equipe_exterieur_id", "label": "equipe_exterieur_id", "type": "str", "required": false, "defaultValue": null}, {"column_type": "field", "field": "vainqueur_id", "label": "vainqueur_id", "type": "str", "required": false, "defaultValue": null}, {"column_type": "field", "field": "est_qualifie", "label": "est_qualifie", "type": "bool", "required": false, "defaultValue": null}, {"column_type": "lookup", "path": "tour", "field": "tour", "lookup_field": "id", "entity": "TournamentRound", "type": "str", "required": true}, {"column_type": "lookup", "path": "match", "field": "match", "lookup_field": "created_at", "entity": "Match", "type": "str", "required": true}]}} dataBinding={{"entity": "BracketSlot", "endpoint": "/bracketslot/"}} />
      </main>
    </div>    </div>
  );
};

export default Bracketslot;
