import React from "react";
import { TableBlock } from "../components/runtime/TableBlock";

const Lineup: React.FC = () => {
  return (
    <div id="page-lineup-22">
    <div id="ir0ox38" style={{"height": "100vh", "fontFamily": "Arial, sans-serif", "display": "flex", "--chart-color-palette": "default"}}>
      <nav id="ii9n3ig" style={{"width": "250px", "padding": "20px", "display": "flex", "overflowY": "auto", "background": "linear-gradient(135deg, #4b3c82 0%, #5a3d91 100%)", "color": "white", "--chart-color-palette": "default", "flexDirection": "column"}}>
        <h2 id="iaamnae" style={{"fontSize": "24px", "fontWeight": "bold", "marginTop": "0", "marginBottom": "30px", "--chart-color-palette": "default"}}>{"BESSER"}</h2>
        <div id="il7poy6" style={{"display": "flex", "--chart-color-palette": "default", "flexDirection": "column", "flex": "1"}}>
          <a id="iiy8dqg" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/channel">{"Channel"}</a>
          <a id="i2a2lqk" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/channelmember">{"ChannelMember"}</a>
          <a id="i6hi6bw" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/competition">{"Competition"}</a>
          <a id="i8vmpbl" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/favoritecompetition">{"FavoriteCompetition"}</a>
          <a id="iub0wfd" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/favoriteteam">{"FavoriteTeam"}</a>
          <a id="i3oghro" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/friendship">{"Friendship"}</a>
          <a id="i6949bw" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/match">{"Match"}</a>
          <a id="i2p0vbv" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/matchevent">{"MatchEvent"}</a>
          <a id="ibdohex" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/message">{"Message"}</a>
          <a id="i3juafx" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/notification">{"Notification"}</a>
          <a id="i2bnok6" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/player">{"Player"}</a>
          <a id="icgemhr" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/reaction">{"Reaction"}</a>
          <a id="i5joekm" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/sport">{"Sport"}</a>
          <a id="i3ok7ey" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/standing">{"Standing"}</a>
          <a id="iwon2gh" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/team">{"Team"}</a>
          <a id="isn0d9a" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/user">{"User"}</a>
          <a id="irm7pp1" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/matchstatistics">{"MatchStatistics"}</a>
          <a id="i6spjbi" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/favoriteplayer">{"FavoritePlayer"}</a>
          <a id="i509rck" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/tournamentround">{"TournamentRound"}</a>
          <a id="idfm4d4" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/bracketslot">{"BracketSlot"}</a>
          <a id="i3qi4dn" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/mediafile">{"MediaFile"}</a>
          <a id="icpo2tt" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/stadium">{"Stadium"}</a>
          <a id="i1zv2lg" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "rgba(255,255,255,0.2)", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/lineup">{"Lineup"}</a>
          <a id="iv9cxvl" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/lineupplayer">{"LineupPlayer"}</a>
          <a id="i0oxblg" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/prematchodds">{"PreMatchOdds"}</a>
          <a id="imwlo6g" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/matchpreview">{"MatchPreview"}</a>
          <a id="inzt8g4" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/tennisset">{"TennisSet"}</a>
        </div>
        <p id="ia86jn4" style={{"fontSize": "11px", "paddingTop": "20px", "marginTop": "auto", "textAlign": "center", "opacity": "0.8", "borderTop": "1px solid rgba(255,255,255,0.2)", "--chart-color-palette": "default"}}>{"© 2026 BESSER. All rights reserved."}</p>
      </nav>
      <main id="izo9h49" style={{"padding": "40px", "overflowY": "auto", "background": "#f5f5f5", "--chart-color-palette": "default", "flex": "1"}}>
        <h1 id="ik0lunr" style={{"fontSize": "32px", "marginTop": "0", "marginBottom": "10px", "color": "#333", "--chart-color-palette": "default"}}>{"Lineup"}</h1>
        <p id="iluv0bk" style={{"marginBottom": "30px", "color": "#666", "--chart-color-palette": "default"}}>{"Manage Lineup data"}</p>
        <TableBlock id="table-lineup-22" styles={{"width": "100%", "minHeight": "400px", "--chart-color-palette": "default"}} title="Lineup List" options={{"showHeader": true, "stripedRows": false, "showPagination": true, "rowsPerPage": 5, "actionButtons": true, "columns": [{"label": "Id", "column_type": "field", "field": "id", "type": "str", "required": true}, {"label": "Formation", "column_type": "field", "field": "formation", "type": "str", "required": true}, {"label": "Statut", "column_type": "field", "field": "statut", "type": "enum", "options": ["annulee", "officielle", "provisoire"], "required": true}, {"label": "Publiee Le", "column_type": "field", "field": "publiee_le", "type": "datetime", "required": true}, {"label": "Est Domicile", "column_type": "field", "field": "est_domicile", "type": "bool", "required": true}, {"label": "Role Double", "column_type": "field", "field": "role_double", "type": "str", "required": true}, {"label": "Match", "column_type": "lookup", "path": "match", "entity": "Match", "field": "created_at", "type": "datetime", "required": true}, {"label": "Equipe", "column_type": "lookup", "path": "equipe", "entity": "Team", "field": "abreviation", "type": "str", "required": true}, {"label": "Joueurs", "column_type": "lookup", "path": "joueurs", "entity": "LineupPlayer", "field": "id", "type": "list", "required": true}], "formColumns": [{"column_type": "field", "field": "id", "label": "id", "type": "str", "required": true, "defaultValue": null}, {"column_type": "field", "field": "formation", "label": "formation", "type": "str", "required": false, "defaultValue": null}, {"column_type": "field", "field": "statut", "label": "statut", "type": "enum", "required": true, "defaultValue": null, "options": ["annulee", "officielle", "provisoire"]}, {"column_type": "field", "field": "publiee_le", "label": "publiee_le", "type": "datetime", "required": false, "defaultValue": null}, {"column_type": "field", "field": "est_domicile", "label": "est_domicile", "type": "bool", "required": true, "defaultValue": null}, {"column_type": "field", "field": "role_double", "label": "role_double", "type": "str", "required": false, "defaultValue": null}, {"column_type": "lookup", "path": "match", "field": "match", "lookup_field": "created_at", "entity": "Match", "type": "str", "required": true}, {"column_type": "lookup", "path": "equipe", "field": "equipe", "lookup_field": "abreviation", "entity": "Team", "type": "str", "required": true}, {"column_type": "lookup", "path": "joueurs", "field": "joueurs", "lookup_field": "id", "entity": "LineupPlayer", "type": "list", "required": true}]}} dataBinding={{"entity": "Lineup", "endpoint": "/lineup/"}} />
      </main>
    </div>    </div>
  );
};

export default Lineup;
