import React from "react";
import { TableBlock } from "../components/runtime/TableBlock";

const Matchevent: React.FC = () => {
  return (
    <div id="page-matchevent-7">
    <div id="il8dwv" style={{"height": "100vh", "fontFamily": "Arial, sans-serif", "display": "flex", "--chart-color-palette": "default"}}>
      <nav id="io29zq" style={{"width": "250px", "padding": "20px", "display": "flex", "overflowY": "auto", "background": "linear-gradient(135deg, #4b3c82 0%, #5a3d91 100%)", "color": "white", "--chart-color-palette": "default", "flexDirection": "column"}}>
        <h2 id="irqv6g" style={{"fontSize": "24px", "fontWeight": "bold", "marginTop": "0", "marginBottom": "30px", "--chart-color-palette": "default"}}>{"BESSER"}</h2>
        <div id="icph3k" style={{"display": "flex", "--chart-color-palette": "default", "flexDirection": "column", "flex": "1"}}>
          <a id="ibhhii" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/channel">{"Channel"}</a>
          <a id="im3f8e" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/channelmember">{"ChannelMember"}</a>
          <a id="id2yjh" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/competition">{"Competition"}</a>
          <a id="ircj89" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/favoritecompetition">{"FavoriteCompetition"}</a>
          <a id="itw43j" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/favoriteteam">{"FavoriteTeam"}</a>
          <a id="itp4ok" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/friendship">{"Friendship"}</a>
          <a id="i84o3r" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/match">{"Match"}</a>
          <a id="i8wumc" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "rgba(255,255,255,0.2)", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/matchevent">{"MatchEvent"}</a>
          <a id="iwp2fk" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/message">{"Message"}</a>
          <a id="isr579" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/notification">{"Notification"}</a>
          <a id="iigbgx" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/player">{"Player"}</a>
          <a id="idy7ss" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/reaction">{"Reaction"}</a>
          <a id="ikqtiu" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/sport">{"Sport"}</a>
          <a id="iyilei" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/standing">{"Standing"}</a>
          <a id="i15ixv" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/team">{"Team"}</a>
          <a id="is09ti" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/user">{"User"}</a>
          <a id="is40gq" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/matchstatistics">{"MatchStatistics"}</a>
          <a id="i1kt0h" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/favoriteplayer">{"FavoritePlayer"}</a>
          <a id="icfcjg" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/tournamentround">{"TournamentRound"}</a>
          <a id="i1bm3f" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/bracketslot">{"BracketSlot"}</a>
          <a id="iws8hf" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/mediafile">{"MediaFile"}</a>
          <a id="if31sf" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/stadium">{"Stadium"}</a>
          <a id="i94q99" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/lineup">{"Lineup"}</a>
          <a id="iyljxg" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/lineupplayer">{"LineupPlayer"}</a>
          <a id="i5g689" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/prematchodds">{"PreMatchOdds"}</a>
          <a id="i6p8xj" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/matchpreview">{"MatchPreview"}</a>
          <a id="i2xcjg" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/tennisset">{"TennisSet"}</a>
        </div>
        <p id="i7fnau" style={{"fontSize": "11px", "paddingTop": "20px", "marginTop": "auto", "textAlign": "center", "opacity": "0.8", "borderTop": "1px solid rgba(255,255,255,0.2)", "--chart-color-palette": "default"}}>{"© 2026 BESSER. All rights reserved."}</p>
      </nav>
      <main id="itszyw" style={{"padding": "40px", "overflowY": "auto", "background": "#f5f5f5", "--chart-color-palette": "default", "flex": "1"}}>
        <h1 id="id1bak" style={{"fontSize": "32px", "marginTop": "0", "marginBottom": "10px", "color": "#333", "--chart-color-palette": "default"}}>{"MatchEvent"}</h1>
        <p id="ip15ha" style={{"marginBottom": "30px", "color": "#666", "--chart-color-palette": "default"}}>{"Manage MatchEvent data"}</p>
        <TableBlock id="table-matchevent-7" styles={{"width": "100%", "minHeight": "400px", "--chart-color-palette": "default"}} title="MatchEvent List" options={{"showHeader": true, "stripedRows": false, "showPagination": true, "rowsPerPage": 5, "actionButtons": true, "columns": [{"label": "Created At", "column_type": "field", "field": "created_at", "type": "datetime", "required": true}, {"label": "Description", "column_type": "field", "field": "description", "type": "str", "required": true}, {"label": "Id", "column_type": "field", "field": "id", "type": "str", "required": true}, {"label": "Minute", "column_type": "field", "field": "minute", "type": "int", "required": true}, {"label": "Type", "column_type": "field", "field": "type", "type": "enum", "options": ["ace", "autre", "break_tennis", "but", "carton_jaune", "carton_rouge", "double_faute", "drop", "essai", "faute", "hors_jeu", "jeu_gagne", "mele_accordee", "penalty", "remplacement", "set_gagne", "tie_break", "transformation"], "required": true}, {"label": "Joueur", "column_type": "lookup", "path": "joueur", "entity": "Player", "field": "date_naissance", "type": "datetime", "required": false}, {"label": "Equipe", "column_type": "lookup", "path": "equipe", "entity": "Team", "field": "abreviation", "type": "str", "required": false}, {"label": "Match", "column_type": "lookup", "path": "match", "entity": "Match", "field": "created_at", "type": "datetime", "required": true}], "formColumns": [{"column_type": "field", "field": "created_at", "label": "created_at", "type": "datetime", "required": true, "defaultValue": null}, {"column_type": "field", "field": "description", "label": "description", "type": "str", "required": true, "defaultValue": null}, {"column_type": "field", "field": "id", "label": "id", "type": "str", "required": true, "defaultValue": null}, {"column_type": "field", "field": "minute", "label": "minute", "type": "int", "required": true, "defaultValue": null}, {"column_type": "field", "field": "type", "label": "type", "type": "enum", "required": true, "defaultValue": null, "options": ["ace", "autre", "break_tennis", "but", "carton_jaune", "carton_rouge", "double_faute", "drop", "essai", "faute", "hors_jeu", "jeu_gagne", "mele_accordee", "penalty", "remplacement", "set_gagne", "tie_break", "transformation"]}, {"column_type": "lookup", "path": "joueur", "field": "joueur", "lookup_field": "date_naissance", "entity": "Player", "type": "str", "required": false}, {"column_type": "lookup", "path": "match", "field": "match", "lookup_field": "created_at", "entity": "Match", "type": "str", "required": true}, {"column_type": "lookup", "path": "equipe", "field": "equipe", "lookup_field": "abreviation", "entity": "Team", "type": "str", "required": false}]}} dataBinding={{"entity": "MatchEvent", "endpoint": "/matchevent/"}} />
      </main>
    </div>    </div>
  );
};

export default Matchevent;
