import React from "react";
import { TableBlock } from "../components/runtime/TableBlock";

const Reaction: React.FC = () => {
  return (
    <div id="page-reaction-11">
    <div id="iz1u9a" style={{"height": "100vh", "fontFamily": "Arial, sans-serif", "display": "flex", "--chart-color-palette": "default"}}>
      <nav id="iyqgsw" style={{"width": "250px", "padding": "20px", "display": "flex", "overflowY": "auto", "background": "linear-gradient(135deg, #4b3c82 0%, #5a3d91 100%)", "color": "white", "--chart-color-palette": "default", "flexDirection": "column"}}>
        <h2 id="ivah1p" style={{"fontSize": "24px", "fontWeight": "bold", "marginTop": "0", "marginBottom": "30px", "--chart-color-palette": "default"}}>{"BESSER"}</h2>
        <div id="iuu6qg" style={{"display": "flex", "--chart-color-palette": "default", "flexDirection": "column", "flex": "1"}}>
          <a id="igz1fm" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/channel">{"Channel"}</a>
          <a id="is4xkf" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/channelmember">{"ChannelMember"}</a>
          <a id="io15ou" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/competition">{"Competition"}</a>
          <a id="i3458v" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/favoritecompetition">{"FavoriteCompetition"}</a>
          <a id="i79hkf" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/favoriteteam">{"FavoriteTeam"}</a>
          <a id="iqbq7c" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/friendship">{"Friendship"}</a>
          <a id="ikeb86" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/match">{"Match"}</a>
          <a id="ib917l" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/matchevent">{"MatchEvent"}</a>
          <a id="idijo8" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/message">{"Message"}</a>
          <a id="ifvxfr" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/notification">{"Notification"}</a>
          <a id="i1z3xj" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/player">{"Player"}</a>
          <a id="iwpfoi" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "rgba(255,255,255,0.2)", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/reaction">{"Reaction"}</a>
          <a id="ijbc5j" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/sport">{"Sport"}</a>
          <a id="ilcme1" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/standing">{"Standing"}</a>
          <a id="iunz03" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/team">{"Team"}</a>
          <a id="i787qv" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/user">{"User"}</a>
          <a id="i5zu9o" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/matchstatistics">{"MatchStatistics"}</a>
          <a id="i54z6g" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/favoriteplayer">{"FavoritePlayer"}</a>
          <a id="i3ch0n" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/tournamentround">{"TournamentRound"}</a>
          <a id="i2yf7v" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/bracketslot">{"BracketSlot"}</a>
          <a id="i4fn7a" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/mediafile">{"MediaFile"}</a>
          <a id="ioz9rn" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/stadium">{"Stadium"}</a>
          <a id="i5bi7z" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/lineup">{"Lineup"}</a>
          <a id="iukn4l" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/lineupplayer">{"LineupPlayer"}</a>
          <a id="imdooh" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/prematchodds">{"PreMatchOdds"}</a>
          <a id="imzjsp" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/matchpreview">{"MatchPreview"}</a>
          <a id="imzhye" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/tennisset">{"TennisSet"}</a>
        </div>
        <p id="it7vwv" style={{"fontSize": "11px", "paddingTop": "20px", "marginTop": "auto", "textAlign": "center", "opacity": "0.8", "borderTop": "1px solid rgba(255,255,255,0.2)", "--chart-color-palette": "default"}}>{"© 2026 BESSER. All rights reserved."}</p>
      </nav>
      <main id="i277v9" style={{"padding": "40px", "overflowY": "auto", "background": "#f5f5f5", "--chart-color-palette": "default", "flex": "1"}}>
        <h1 id="ig1ard" style={{"fontSize": "32px", "marginTop": "0", "marginBottom": "10px", "color": "#333", "--chart-color-palette": "default"}}>{"Reaction"}</h1>
        <p id="iugsck" style={{"marginBottom": "30px", "color": "#666", "--chart-color-palette": "default"}}>{"Manage Reaction data"}</p>
        <TableBlock id="table-reaction-11" styles={{"width": "100%", "minHeight": "400px", "--chart-color-palette": "default"}} title="Reaction List" options={{"showHeader": true, "stripedRows": false, "showPagination": true, "rowsPerPage": 5, "actionButtons": true, "columns": [{"label": "Created At", "column_type": "field", "field": "created_at", "type": "datetime", "required": true}, {"label": "Id", "column_type": "field", "field": "id", "type": "str", "required": true}, {"label": "Type", "column_type": "field", "field": "type", "type": "enum", "options": ["choc", "coeur", "colere", "feu", "pouce_haut", "rire", "triste"], "required": true}, {"label": "Message", "column_type": "lookup", "path": "message", "entity": "Message", "field": "content", "type": "str", "required": true}, {"label": "User", "column_type": "lookup", "path": "user", "entity": "User", "field": "avatar_url", "type": "str", "required": true}], "formColumns": [{"column_type": "field", "field": "created_at", "label": "created_at", "type": "datetime", "required": true, "defaultValue": null}, {"column_type": "field", "field": "id", "label": "id", "type": "str", "required": true, "defaultValue": null}, {"column_type": "field", "field": "type", "label": "type", "type": "enum", "required": true, "defaultValue": null, "options": ["choc", "coeur", "colere", "feu", "pouce_haut", "rire", "triste"]}, {"column_type": "lookup", "path": "message", "field": "message", "lookup_field": "content", "entity": "Message", "type": "str", "required": true}, {"column_type": "lookup", "path": "user", "field": "user", "lookup_field": "username", "entity": "User", "type": "str", "required": true}]}} dataBinding={{"entity": "Reaction", "endpoint": "/reaction/"}} />
      </main>
    </div>    </div>
  );
};

export default Reaction;
