import React from "react";
import { TableBlock } from "../components/runtime/TableBlock";

const Tennisset: React.FC = () => {
  return (
    <div id="page-tennisset-26">
    <div id="icofyxf" style={{"height": "100vh", "fontFamily": "Arial, sans-serif", "display": "flex", "--chart-color-palette": "default"}}>
      <nav id="i0crgyb" style={{"width": "250px", "padding": "20px", "display": "flex", "overflowY": "auto", "background": "linear-gradient(135deg, #4b3c82 0%, #5a3d91 100%)", "color": "white", "--chart-color-palette": "default", "flexDirection": "column"}}>
        <h2 id="ig1g3ri" style={{"fontSize": "24px", "fontWeight": "bold", "marginTop": "0", "marginBottom": "30px", "--chart-color-palette": "default"}}>{"BESSER"}</h2>
        <div id="ismi5ww" style={{"display": "flex", "--chart-color-palette": "default", "flexDirection": "column", "flex": "1"}}>
          <a id="icc73ak" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/channel">{"Channel"}</a>
          <a id="id8u3di" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/channelmember">{"ChannelMember"}</a>
          <a id="ivad8ni" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/competition">{"Competition"}</a>
          <a id="il7a8ji" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/favoritecompetition">{"FavoriteCompetition"}</a>
          <a id="ia79yzf" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/favoriteteam">{"FavoriteTeam"}</a>
          <a id="ixxzv3i" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/friendship">{"Friendship"}</a>
          <a id="iksmhl2" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/match">{"Match"}</a>
          <a id="i0b9ed8" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/matchevent">{"MatchEvent"}</a>
          <a id="i9o766v" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/message">{"Message"}</a>
          <a id="ia50zjp" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/notification">{"Notification"}</a>
          <a id="iy6ght8" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/player">{"Player"}</a>
          <a id="icavz7w" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/reaction">{"Reaction"}</a>
          <a id="io9sbl5" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/sport">{"Sport"}</a>
          <a id="i059jdd" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/standing">{"Standing"}</a>
          <a id="ipp6848" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/team">{"Team"}</a>
          <a id="i278gy3" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/user">{"User"}</a>
          <a id="ilallhi" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/matchstatistics">{"MatchStatistics"}</a>
          <a id="i7pmf48" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/favoriteplayer">{"FavoritePlayer"}</a>
          <a id="i325vcf" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/tournamentround">{"TournamentRound"}</a>
          <a id="itbry89" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/bracketslot">{"BracketSlot"}</a>
          <a id="igvcjel" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/mediafile">{"MediaFile"}</a>
          <a id="ipc7n2l" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/stadium">{"Stadium"}</a>
          <a id="iq19hsq" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/lineup">{"Lineup"}</a>
          <a id="itiz4jc" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/lineupplayer">{"LineupPlayer"}</a>
          <a id="irqhtci" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/prematchodds">{"PreMatchOdds"}</a>
          <a id="itz2dk5" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "transparent", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/matchpreview">{"MatchPreview"}</a>
          <a id="i6nibl1" style={{"padding": "10px 15px", "textDecoration": "none", "marginBottom": "5px", "display": "block", "background": "rgba(255,255,255,0.2)", "color": "white", "borderRadius": "4px", "--chart-color-palette": "default"}} href="/tennisset">{"TennisSet"}</a>
        </div>
        <p id="i56pfdq" style={{"fontSize": "11px", "paddingTop": "20px", "marginTop": "auto", "textAlign": "center", "opacity": "0.8", "borderTop": "1px solid rgba(255,255,255,0.2)", "--chart-color-palette": "default"}}>{"© 2026 BESSER. All rights reserved."}</p>
      </nav>
      <main id="i8is58v" style={{"padding": "40px", "overflowY": "auto", "background": "#f5f5f5", "--chart-color-palette": "default", "flex": "1"}}>
        <h1 id="i0vm1du" style={{"fontSize": "32px", "marginTop": "0", "marginBottom": "10px", "color": "#333", "--chart-color-palette": "default"}}>{"TennisSet"}</h1>
        <p id="itzf3b9" style={{"marginBottom": "30px", "color": "#666", "--chart-color-palette": "default"}}>{"Manage TennisSet data"}</p>
        <TableBlock id="table-tennisset-26" styles={{"width": "100%", "minHeight": "400px", "--chart-color-palette": "default"}} title="TennisSet List" options={{"showHeader": true, "stripedRows": false, "showPagination": true, "rowsPerPage": 5, "actionButtons": true, "columns": [{"label": "Id", "column_type": "field", "field": "id", "type": "str", "required": true}, {"label": "Numero Set", "column_type": "field", "field": "numero_set", "type": "int", "required": true}, {"label": "Jeux J1", "column_type": "field", "field": "jeux_j1", "type": "int", "required": true}, {"label": "Jeux J2", "column_type": "field", "field": "jeux_j2", "type": "int", "required": true}, {"label": "Tb Points J1", "column_type": "field", "field": "tb_points_j1", "type": "int", "required": true}, {"label": "Tb Points J2", "column_type": "field", "field": "tb_points_j2", "type": "int", "required": true}, {"label": "Gagnant Id", "column_type": "field", "field": "gagnant_id", "type": "str", "required": true}, {"label": "Est Termine", "column_type": "field", "field": "est_termine", "type": "bool", "required": true}, {"label": "Match", "column_type": "lookup", "path": "match", "entity": "Match", "field": "created_at", "type": "datetime", "required": true}], "formColumns": [{"column_type": "field", "field": "id", "label": "id", "type": "str", "required": true, "defaultValue": null}, {"column_type": "field", "field": "numero_set", "label": "numero_set", "type": "int", "required": true, "defaultValue": null}, {"column_type": "field", "field": "jeux_j1", "label": "jeux_j1", "type": "int", "required": true, "defaultValue": null}, {"column_type": "field", "field": "jeux_j2", "label": "jeux_j2", "type": "int", "required": true, "defaultValue": null}, {"column_type": "field", "field": "tb_points_j1", "label": "tb_points_j1", "type": "int", "required": false, "defaultValue": null}, {"column_type": "field", "field": "tb_points_j2", "label": "tb_points_j2", "type": "int", "required": false, "defaultValue": null}, {"column_type": "field", "field": "gagnant_id", "label": "gagnant_id", "type": "str", "required": false, "defaultValue": null}, {"column_type": "field", "field": "est_termine", "label": "est_termine", "type": "bool", "required": true, "defaultValue": null}, {"column_type": "lookup", "path": "match", "field": "match", "lookup_field": "created_at", "entity": "Match", "type": "str", "required": true}]}} dataBinding={{"entity": "TennisSet", "endpoint": "/tennisset/"}} />
      </main>
    </div>    </div>
  );
};

export default Tennisset;
